[project]
title = "Gavins Coding Interview Project"
version = "0.1.0"
port = 8501
slug = "gavins-project"  
entrypoint = "main.py"    

[branding]
name = "Gavins Coding Interview Project"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.CropYield_csv]
type = "csv"
path = "data/CropYield2024.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"